# Generated by Django 4.2.2 on 2023-06-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomName', models.CharField(max_length=150, unique=True)),
                ('slugName', models.SlugField(max_length=150)),
            ],
        ),
    ]
