# Generated by Django 4.2.2 on 2023-06-16 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='slugName',
        ),
    ]
